### ISSUE TITLE
Removing embeds when sending link through the bot

### ISSUE THREAD

**Issue by DaeguDude** [TheOdinProject/odin-bot-v2#101]
In discord, auto-embeds are emitted when sending link through the bot. For example, if you call `/callbacks` command in the discord, you'll see this embed.

<img width="803" alt="Screen Shot 2021-02-03 at 10 05 14 AM" src="https://user-images.githubusercontent.com/35420073/106683163-5c0b9800-6607-11eb-931d-766c0d2ba7a5.png">

It'd be nice if we could remove those auto-embeds.

Tasks will be, 

- [x] Find all bot commands that emit the embeds
- [x] Specify the commands where we don't want the embeds on
- [x] Modify those commands to remove embeds

Discord - [Information on disabling auto-embed](https://support.discord.com/hc/en-us/articles/206342858--How-do-I-disable-auto-embed-)

The discussion started [here](https://github.com/TheOdinProject/odin-bot-v2/issues/86)

**Comment by DaeguDude** [comment]
I guess I will work on this.

**Comment by DaeguDude** [comment]
**Find all bot commands that emit the embeds**

___

@I3uckwheat Currently there are 2 commands that emit the auto-embeds

- `/bootcamps`
- `/windows`

<img width="627" alt="Screen Shot 2021-02-16 at 11 19 05 AM" src="https://user-images.githubusercontent.com/35420073/108011209-f0cfb600-7049-11eb-8e82-1706df71ba0c.png">
<img width="635" alt="Screen Shot 2021-02-16 at 11 19 15 AM" src="https://user-images.githubusercontent.com/35420073/108011214-f3321000-7049-11eb-834a-6e93043d4717.png">


which I didn't include 'gif' and youtube embeds(`/motivate`, `/justDoIt`).
And strangely, the `/question` command that started this issue doesn't emit the auto-embeds anymore even though it isn't surrounded by `<>`, which will disable the auto-embed.

**Comment by I3uckwheat** [comment]
@DaeguDude I think we can leave the twitter one. The Odin one can go though.

**Comment by DaeguDude** [comment]
@I3uckwheat I will disable auto embed on `/windows` command and make a PR then
