### ISSUE TITLE
Update /debug for JS and Ruby

### ISSUE THREAD

**Issue by rlmoser99** [TheOdinProject/odin-bot-v2#105]
Since students in the ruby section often ignore the importance of learning debugging as well, it would be great to have a command for both sections. 

Update the /debug command to accept the arguments `js` or `rb`

It was discussed to have the /debug command without arguments to link to wikipedia's debugging page, but I would if it would better to expand the wording of the bot command to something like this:

> Based on the description of your problem, you can get to the root of it using a debugger. Learning how to track down problems like this is an inevitable part of being a developer. 

If the argument `js` is provided, link to (current bot link):
https://developers.google.com/web/tools/chrome-devtools/javascript

If the argument `rb` is provided, link to:
https://www.theodinproject.com/courses/ruby-programming/lessons/debugging#debugging-with-pry-byebug

**Comment by twalton83** [comment]
@aayushmau5 If you were interested in expanding /debug, here's the issue!

**Comment by aayushmau5** [comment]
Would love to work on this.
