### ISSUE TITLE
Reword /question command

### ISSUE THREAD

**Issue by twalton83** [TheOdinProject/odin-bot-v2#111]
In an effort to make the command come off as more of a "call in" rather than a "call out", we'd like to change the wording of the `/question` command from "It looks like you're trying to ask a question! Please give this page a read" to something that may come off a little more friendly, such as "Help others help you, check out this article:". Open to suggestions.

**Completion Criteria**:
- [x] The callback needs to return an update phrase
- [x] The snapshot test for the callback must be updated (see README for how to update snapshot tests)
- [x] All tests must pass

**Comment by thatblindgeye** [comment]
Commenting to claim

**Comment by twalton83** [comment]
Thank you! Please see our README for instructions :)

**Comment by thatblindgeye** [comment]
Possible suggestions for the replacement phrase (I can try shortening them as well if they're too long):

- "We'd love to help you out! Check out this article to help others better understand your question:"
- "Would you mind checking out this article? It'll help others offer the best answer possible to help you."
- "Helping others also helps you. Checking out this article helps others offer you their best answer."
- "There's always someone willing to help! Check out this article really quick to help others help you:"
- "To help make sure others can provide you with their best answer, please take a moment to check out this article:"

Or some concoction of those/the "help others help you" bit?

**Comment by twalton83** [comment]
I prefer the first.
