### ISSUE TITLE
Fix ESLint Errors

### ISSUE THREAD

**Issue by twalton83** [TheOdinProject/odin-bot-v2#116]
Nearly all of our code does not comply with our ESLint configuration, so we will need to manually fix these errors to ensure accuracy, and make decisions for refactoring where necessary. 

**Completion Criteria**:

- [x] ESLint no longer throws any errors or warnings
- [x] All files are linted and fixed

**Comment by JonColman94** [comment]
I'll have a crack at this.

QChai

**Comment by twalton83** [comment]
Thanks, let's discuss in the contributions channel because a bit more thought has to go into a lot of these changes.

**Comment by JonColman94** [comment]
I'd imagine with the latest merge, this issue is resolved unless there are any other pressing issues?

**Comment by twalton83** [comment]
There's still a few warnings that we need to manually resolve. Thanks for the help though! @JonColman94

**Comment by twalton83** [comment]
Closing because all errors are resolved, and warnings are less of a priority and can be targeted in a later bot refactor
