### ISSUE TITLE
Create /xy command

### ISSUE THREAD

**Issue by twalton83** [TheOdinProject/odin-bot-v2#128]
We'd like to add a command to address the "XY Problem". Make the associated message friendly and/or funny, and link to the xyproblem.info. We want something similar to our `/question` command. 

**Completion Criteria**:
- [ ] a new command triggered by `/xy` with a "fun" message that links to the [the XY Problem website](https://xyproblem.info/)
- [ ] unit tests and snapshot tests for the new command (please use the `/question` tests in `help.test.js` as a reference)
- [ ] all tests pass

**Comment by wise-king-sullyman** [comment]
I direct people to that link every so often, I'd be happy to knock this out.

**Comment by twalton83** [comment]
Thanks!

**Comment by twalton83** [comment]
Closed by #129
