### ISSUE TITLE
Create /top command

### ISSUE THREAD

**Issue by twalton83** [TheOdinProject/odin-bot-v2#131]
We need a quick and easy command that links people to https://theodinproject.com/

A similar command to base this off of would be our `/windows` command.

**Completion Criteria:**

- [ ] New command that is triggered by the string "`/top`", with a fun little string prepending it
- [ ] Tested, with all tests passing and a new snapshot
- [ ] Link embed is removed [SEE HERE](https://support.discord.com/hc/en-us/articles/206342858--How-do-I-disable-auto-embed-#:~:text=Pro%20Tip%3A%20If%20you%20want,in%20''%20tags.)

**Comment by bscottnz** [comment]
keen :)

**Comment by twalton83** [comment]
All yours @bscottnz, go ahead and take a gander at our README and ask any questions if need be.
