### ISSUE TITLE
Create /faq command

### ISSUE THREAD

**Issue by CatQueenCodes** [TheOdinProject/odin-bot-v2#132]
We need a quick and easy command that links people to our new discord faq channel: https://discord.com/channels/505093832157691914/823266307293839401/823266549912829992 

A similar command to base this off of would be our /time command. [Check it out here](https://github.com/TheOdinProject/odin-bot-v2/blob/b72ba8be197d0aba83e8d1333078ddaa69c12f96/botCommands/time.js).

**Completion Criteria:**

- [x] New command that is triggered by the string "`/faq`", with a fun little string prepending it along the lines of "Your question has been answered in our faq" (be creative/witty!)
- [ ] Be able to mention people
- [ ] Tested, with all tests passing and a new snapshot
- [ ] Link embed is removed [SEE HERE](https://support.discord.com/hc/en-us/articles/206342858--How-do-I-disable-auto-embed-#:~:text=Pro%20Tip%3A%20If%20you%20want,in%20''%20tags.)

**Comment by Zadag** [comment]
I'll work on this later today.
