### ISSUE TITLE
/code command needs to be a rich embed

### ISSUE THREAD

**Issue by twalton83** [TheOdinProject/odin-bot-v2#137]
We are in the process of moving our commands  to a Rich Embed feature that makes the commands more obvious, and take up less space in the chat. An example of this is below:

<img width="637" alt="Screen Shot 2021-03-23 at 7 29 44 AM" src="https://user-images.githubusercontent.com/22967723/112162717-8ad6d100-8ba9-11eb-8f75-67f3ea230028.png">

https://discordjs.guide/popular-topics/embeds.html#embeds NOTE: We are using v11, please make sure you are reading the instructions for the `RichEmbed` class, not the`MessageEmbed` class.

Our `/code` command will need to have a `title`, a `description`, and a regular `field` for the typical code snippets markdown syntax (the backticks). Focus on changing the format, but not changing the copy where possible. We will want additional `inline-field`s for Repl.it (Javascript/Ruby), CodeSandBox (Webpack/React), and Codepen (Basic HTML/CSS/JS). 

**Completion Criteria**:
- We leverage the `Discord.RichEmbed()` constructor
- We have an embed with the aforementioned fields
- updated snapshot
- correct grammar and spelling
- All tests pass

**Comment by DaeguDude** [comment]
I'll take a crack at this

**Comment by twalton83** [comment]
This one will be a little more involved, and require you run an instance of the bot so we can see what the embed looks like. You good with that?

**Comment by DaeguDude** [comment]
Like run an instance of the bot in my own server to see what the embed looks like?
Is there any time-bound on this?

**Comment by twalton83** [comment]
Yep, we want to make sure we're good with the layout or if we want to make changes. No, not particularly.

**Comment by DaeguDude** [comment]
Yup, I'm good with it.

**Comment by DaeguDude** [comment]
This is the basic embed that I came up with. I have fill in the aforementioned fields, but I
am not too sure this is the look that we want.

I'd appreciate some feedback so I can implement
![Screen Shot 2021-03-29 at 2 45 54 PM](https://user-images.githubusercontent.com/35420073/112792115-d30c5c80-909d-11eb-8fbe-a3526f4b8c99.png)

**Comment by twalton83** [comment]
There’s a typo with “snippets”

**Comment by DaeguDude** [comment]
Oops, yeah. I will fix it before committing it.
But overall the look of the embed is okay?

**Comment by twalton83** [comment]
I like the embed. I know you said you’ll proofread, but let’s change “to the others” in the first sentence to “with others”. 

Let’s change the next header to “Sharing Code On Discord”.

I think showing multi line code and then showing it again with syntax highlighting is redundant, we want people to highlight by default so let’s just combine the first bit of text but use the syntax highlighting example. I know I said we wouldn’t change the copy but since we’re already here and making this command better, let’s go for it.

**Comment by twalton83** [comment]
ah, I actually just realized that we also mention users in this command. Let’s not forget to add that capability too. It can go in the message under the first header.

**Comment by twalton83** [comment]
Closed by #144
