### ISSUE TITLE
/help command needs to return a MessageEmbed

### ISSUE THREAD

**Issue by twalton83** [TheOdinProject/odin-bot-v2#140]
We are in the process of moving our commands to a Message Embed feature that makes the commands more obvious, and take up less space in the chat. An example of this is below. 
<img width="831" alt="Screen Shot 2021-03-30 at 7 56 51 PM" src="https://user-images.githubusercontent.com/22967723/113084021-1516ca80-9192-11eb-880b-3696e6715a65.png">

[Embed Guide](https://discordjs.guide/popular-topics/embeds.html#embed-preview) 

Our `/help` command will need to have a `title`, a `description`, and `field`s with their own values for each separate "bullet" in the command as it currently stands. 

**Completion Criteria**:
- [ ] We leverage the `Discord.MessageEmbed()` constructor 
- [ ] We have an embed with the aforementioned fields
- [ ] Updated snapshot
- [ ] Correct grammar and spelling
- [ ] All tests pass

Please run your own instance of the bot and provide a screenshot of the embed in your PR.

**Comment by mdlugosz1** [comment]
I can deal with this one.

**Comment by twalton83** [comment]
Sure, let’s talk about it on Discord in the contributions channel.

**Comment by twalton83** [comment]
Closed with #167
