### ISSUE TITLE
/data command needs new copy and needs to be converted to a MessageEmbed

### ISSUE THREAD

**Issue by twalton83** [TheOdinProject/odin-bot-v2#145]
We are in the process of moving our commands  to a MessageEmbed feature that makes the commands more obvious, and take up less space in the chat. An example of this is below:

<img width="831" alt="Screen Shot 2021-03-30 at 7 56 51 PM" src="https://user-images.githubusercontent.com/22967723/113084021-1516ca80-9192-11eb-880b-3696e6715a65.png">

[Embed Guide](https://discordjs.guide/popular-topics/embeds.html#embed-preview) 

Additionally, we want to update our /data command text to be more friendly and descriptive, so people are more inclined to understand what was wrong with their question.

Our `/data` Message Embed will need to have a `title`, a URL that links to [this website](https://dontasktoask.com/), and a new `description` that says: 

> Instead of asking if anyone can help you, ask your question outright so people *can* help you! 
> **Bad**: "Hey, does anyone know about how to set CSS styles with Javascript?"
> **Good**: 
> "Hey, I'm having trouble setting CSS styles via Javascript. 
> Here's my code:
>  ```
>  Code snippet 
> ```
>  And here is the error I'm receiving: 
>  `Cannot set attribute 'style' of null`"

**Completion Criteria**:
- [ ] We leverage the `Discord.MessageEmbed()` constructor
- [ ] We have an embed with the aforementioned fields
- [ ] updated snapshot test
- [ ] correct grammar and spelling
- [ ] All tests pass
- [ ] Your PR includes a screenshot of the new embed.

**Comment by twalton83** [comment]
Blocked by #151

**Comment by DoviMaj** [comment]
me me me

**Comment by twalton83** [comment]
Closed by #163
