### ISSUE TITLE
/question command needs to return a MessageEmbed

### ISSUE THREAD

**Issue by twalton83** [TheOdinProject/odin-bot-v2#146]
We are in the process of moving our commands to a MessageEmbed feature that makes the commands more obvious, and take up less space in the chat. An example of this is below. 
<img width="831" alt="Screen Shot 2021-03-30 at 7 56 51 PM" src="https://user-images.githubusercontent.com/22967723/113084021-1516ca80-9192-11eb-880b-3696e6715a65.png">

[Embed Guide](https://discordjs.guide/popular-topics/embeds.html#embed-preview)

Our `/question` command will need to have a `title` with the value "Asking Great Questions", a `description` with the current command's string, including [this article](https://medium.com/@gordon_zhu/how-to-be-great-at-asking-questions-e37be04d0603). 

**Completion Criteria**:
- [ ] We leverage the `Discord.MessageEmbed()` constructor 
- [ ] We have an embed with the aforementioned fields
- [ ] Updated snapshot
- [ ] Correct grammar and spelling
- [ ] All tests pass

**Please run your own instance of the bot and provide a screenshot of the embed in your PR.**

**Comment by twalton83** [comment]
Blocked by #151

**Comment by fernie-cpu** [comment]
I'd like to get this one too when we're good to go
