### ISSUE TITLE
/faq command needs to return a MessageEmbed

### ISSUE THREAD

**Issue by twalton83** [TheOdinProject/odin-bot-v2#147]
We are in the process of moving our commands to a MessageEmbed feature that makes the commands more obvious, and take up less space in the chat. An example of this is below. 
<img width="831" alt="Screen Shot 2021-03-30 at 7 56 51 PM" src="https://user-images.githubusercontent.com/22967723/113084021-1516ca80-9192-11eb-880b-3696e6715a65.png">

[Embed Guide](https://discordjs.guide/popular-topics/embeds.html#embed-preview)

Our `/faq` command will need to have a `title` with the value "Frequently Asked Questions", a `description` with the value "The definition of insanity is answering the same question over and over again when we have an #FAQ!  Help us stay sane by giving it a read." 

**Completion Criteria**:
- [ ] We leverage the `Discord.MessageEmbed()` constructor 
- [ ] We have an embed with the aforementioned fields
- [ ] Updated snapshot
- [ ] Correct grammar and spelling
- [ ] All tests pass

Please run your own instance of the bot and provide a screenshot of the embed in your PR.

**Comment by sheacronin** [comment]
Hi, I'm interested in taking this on!

**Comment by twalton83** [comment]
Thanks @sheacronin!
