### ISSUE TITLE
/windows command should return a MessageEmbed

### ISSUE THREAD

**Issue by twalton83** [TheOdinProject/odin-bot-v2#148]
We are in the process of moving our commands to a MessageEmbed feature that makes the commands more obvious, and take up less space in the chat. An example of this is below. 
<img width="831" alt="Screen Shot 2021-03-30 at 7 56 51 PM" src="https://user-images.githubusercontent.com/22967723/113084021-1516ca80-9192-11eb-880b-3696e6715a65.png">

[Embed Guide](https://discordjs.guide/popular-topics/embeds.html#embed-preview) 

Our `/windows` command embed will need a `description` with the value set to our current copy, sans the lesson's URL. We should also use `setURL` and set it to the URL in our current string. Additionally, I would like to provide emphasis around the "The Odin Project does not support Windows, WSL, or any OS outside of our recommendations.", and have this part of the string now be bold.

**Completion Criteria**:
- [ ] We leverage the `Discord.MessageEmbed()` constructor 
- [ ] We have an embed with the aforementioned fields
- [ ] Updated snapshot
- [ ] Correct grammar and spelling
- [ ] All tests pass

Please run your own instance of the bot and provide a screenshot of the embed in your PR.

**Comment by twalton83** [comment]
Blocked by #151

**Comment by mdlugosz1** [comment]
I'd be happy to work on this issue

**Comment by twalton83** [comment]
Thanks!
