### ISSUE TITLE
/debug command needs to return a MessageEmbed

### ISSUE THREAD

**Issue by twalton83** [TheOdinProject/odin-bot-v2#149]
We are in the process of moving our commands to a Message Embed feature that makes the commands more obvious, and take up less space in the chat. An example can be seen below:

<img width="831" alt="Screen Shot 2021-03-30 at 7 56 51 PM" src="https://user-images.githubusercontent.com/22967723/113084021-1516ca80-9192-11eb-880b-3696e6715a65.png">

[Embed Guide](https://discordjs.guide/popular-topics/embeds.html#embed-preview) 

- Our `/debug` command embed will need a `title`, set to the value "Debugging".
- We will need a `description` with the value set to "'Based on the description of your problem, you can get to the root of it using a debugger. Learning how to track down problems like this is an inevitable part of being a developer."
- We should also use `setURL` and set it to [this article](https://en.wikipedia.org/wiki/Debugging). 
- Additionally, we need two `field`s, titled "Javascript" and "Ruby" , with each respective debugger link currently found in our `/debug` command.

Because of these changes, the command will no longer need to take in arguments since we are providing both the Ruby and JS resources, as well as the Wikipedia article in the title. Note that our tests will need to be updated to reflect this. 

**Completion Criteria**:
- [ ] We leverage the `Discord.MessageEmbed()` constructor 
- [ ] We have an embed with the aforementioned fields
- [ ] Updated snapshot
- [ ] Correct grammar and spelling
- [ ] `js` and `ruby` arguments are removed from the logic of the command
- [ ] Tests are updated to omit testing for `ruby` or `js` arguments
- [ ] All tests pass

Please run your own instance of the bot and provide a screenshot of the embed in your PR.

**Comment by fernie-cpu** [comment]
Mine

**Comment by twalton83** [comment]
Blocked by #151
