### ISSUE TITLE
/leaderboard command should return a MessageEmbed

### ISSUE THREAD

**Issue by twalton83** [TheOdinProject/odin-bot-v2#150]
We are in the process of moving our commands to a MessageEmbed feature that makes the commands more obvious, and take up less space in the chat. An example of this is below. 
<img width="831" alt="Screen Shot 2021-03-30 at 7 56 51 PM" src="https://user-images.githubusercontent.com/22967723/113084021-1516ca80-9192-11eb-880b-3696e6715a65.png">

[Embed Guide](https://discordjs.guide/popular-topics/embeds.html#embed-preview) 

Our `/leaderboard` command will need to have a `title` with the value of "Leaderboard", and the `description` should contain the string of users and their points that is returned from our current command.

**Completion Criteria**:
- [ ] We leverage the `Discord.MessageEmbed()` constructor 
- [ ] We have an embed with the aforementioned fields
- [ ] Updated snapshot
- [ ] Correct grammar and spelling
- [ ] All tests pass

Please run your own instance of the bot and provide a screenshot of the embed in your PR.

**Comment by timjacksonm** [comment]
I will take this one.
