### ISSUE TITLE
Pre-commit hook should check for ESLint

### ISSUE THREAD

**Issue by twalton83** [TheOdinProject/odin-bot-v2#161]
Many contributors push code that fails our CircleCI checks because they are not forced to lint their code at any point in the Git process. 
We should: 

- Update Husky to check for linting errors 
- Create a pre-*commit* hook for the above

**Comment by BrianWisniewski** [comment]
I would be happy to take a crack at this one if it is not yet claimed.

**Comment by twalton83** [comment]
I already made the pr, thanks though @BrianWisniewski

**Comment by twalton83** [comment]
Closed with #165
