### ISSUE TITLE
Point should not be awarded in #bot-spam-playground

### ISSUE THREAD

**Issue by twalton83** [TheOdinProject/odin-bot-v2#168]
# User Stories
As a maintainer, I would like to prevent the abuse of the points system in a largely unmonitored spam channel, so we should add a restriction to the `awardPoints` function that determines if the channel is the #bot-spam-playground, and returns a message stating that you can't award points there. 

# Completion Criteria

- [x] points are unable to be awarded in specified channel(s)
- [x] config file that allows us to add an array of channel IDs that points cannot be awarded in (optional)
- [x] message letting awarder know that points cannot be added in this channel (private message only seen by awarder?)
- [x] unit tests

**Comment by BrianWisniewski** [comment]
I'll give this one a shot.

**Comment by twalton83** [comment]
Let’s discuss the approach because this also requires one to write tests and mocks.

**Comment by twalton83** [comment]
@BrianWisniewski To reiterate what I’ve mentioned on Discord (and for transparency so all who read the issue can see it)- this might be better suited towards a maintainer who has intimate knowledge of our tests and what we need here. We currently have a feature freeze and won’t be prioritizing implementing this, but I appreciate you asking.
