### ISSUE TITLE
Extend ++ command to award double points for good questions

### ISSUE THREAD

**Issue by twalton83** [TheOdinProject/odin-bot-v2#176]
# Description
In an effort to improve the Discord community, the ability for maintainers and core members to award 2 points for good questions should be implemented.

# Acceptance Criteria
- [ ] Users with a maintainer or core role are able to use `@user ?++` to award points
- [ ] Using the new API query params, the above command should award the mentioned user two points 
- [ ] A message stating something like `Double points for a great question! @user has XX points!`
- [ ] Tests

**Comment by timothyling1994** [comment]
hey @twalton83, can I work on this?

**Comment by twalton83** [comment]
If you can write the corresponding tests for this, absolutely.

**Comment by twalton83** [comment]
@timothyling1994 Will you be taking this issue?

**Comment by timothyling1994** [comment]
@twalton83 hey sorry for the delay. yes! i'll take this issue. I'll spend some time this weekend to work on it.

**Comment by twalton83** [comment]
Please let us know if you have any questions about the testing or DiscordJS.

**Comment by timothyling1994** [comment]
@twalton83 I took a look at the codebase and had a couple of questions:

1) In the config file, there's a points bot token (which is rightfully obscured in the .env file) that is required to send an authenticated request to the TOP points API endpoint (**https://www.theodinproject.com/api/points?discord_id=${discordId}**). Is there a test API endpoint that I could use for testing? Or did you want me to forgo testing the backend side of things and just mock the calls when testing?

`const config = {
  pointsbot: {
    token: process.env.POINTSBOT_TOKEN,
  },
  noPointsChannels: ['513125912070455296'],
};`

`POINTSBOT_TOKEN=xxxxx`

2) When updating the points for a user, we make a call to the API endpoint shown below. Is there an argument that the endpoint takes to increment points by a certain value? Or should I just call the endpoint twice to increment by 2?

`async function addPointsToUser(discordId) {
  try {
    const pointsBotResponse = await axios.post(
      `https://www.theodinproject.com/api/points?discord_id=${discordId}`,
    );
    return pointsBotResponse.data;
  } catch (err) {
    throw new Error(err.message);
  }
}`

**Comment by twalton83** [comment]
In these units tests we are testing that the function itself works, not that the API is hit, so we should mock axios (see elsewhere in the test file for an example). 

Refer to this issue for bullet 2- no need to hit the API twice now: https://github.com/TheOdinProject/odin-bot-v2/issues/175

**Comment by twalton83** [comment]
@timothyling1994 Do we have any update? :D

**Comment by timothyling1994** [comment]
@twalton83 
The implementation, test cases, and linting have been completed. There's one last thing before I'm ready to rebase on master. 

I'm still unclear on how to POST the API endpoint to add 2 points to a specific user. The issue you linked above (#175) seems to be about filtering the leaderboard data when using GET on the endpoint. I'm unclear on what parameter I need to pass in the API call to add 2 points. 

Let me know if I'm misinterrepting anything in that ticket. I can also hop on Discord if you wanted to chat further there.

**Comment by twalton83** [comment]
@KevinMulhern do you mind clarifying or perhaps pointing this user to the POST route?

**Comment by KevinMulhern** [comment]
@twalton83 sorry for the delay.

The post route takes a value param for the points amount, for example:
`https://www.theodinproject.com/api/points?discord_id=${discordId}&value=2);`

**Comment by twalton83** [comment]
@timothyling1994 Did the above clear this up for you?

**Comment by timothyling1994** [comment]
@twalton83 yes this cleared it up - I've made the appropriate changes. Currently reviewing merge differences between my local repo and the current upstream main branch. I should be able to submit my PR tomorrow. Apologies on the delay

**Comment by timothyling1994** [comment]
@twalton83 Created the PR above. Let me know if you have any questions or comments!
