### ISSUE TITLE
/points command should show author's points if no one is mentioned

### ISSUE THREAD

**Issue by twalton83** [TheOdinProject/odin-bot-v2#180]
Currently the `/points` command requires the author to @ mention themselves if they would like to check their own points. It is more intuitive and common of other bots to check the author's own points without needing to mention themselves.

**Completion Criteria:**

- [ ] The `/points` command takes in the `author` as an argument
- [ ] The [`/points` command](https://github.com/TheOdinProject/odin-bot-v2/blob/c741e6642ee4c3709f6afd5f35bb04aaaa6c0f39/botCommands/points.js#L161) should return the author's own points if they have not mentioned another user in their message
- [ ] [Regex test is updated](https://github.com/TheOdinProject/odin-bot-v2/blob/main/botCommands/points.test.js#L480) to include a case where a user does not mention another user in their message.

**Comment by lstewart11** [comment]
Is this still available to be worked on?

**Comment by twalton83** [comment]
This is closed, sorry about that!
