### ISSUE TITLE
Full Leaderboard Link isn't up-to-date

### ISSUE THREAD

**Issue by nearmint** [TheOdinProject/odin-bot-v2#21]
In odin-bot-v2/botCommands/points.js the URL https://odin-bot.github.io is mentioned to look at the full leaderboard for Odin Points. But for some reason the points displayed there are not up-to-date.

I'd love to help out in fixing this problem, but I don't know where to start. I can't even find the corresponding file for https://odin-bot.github.io.

**Comment by codyloyd** [comment]
the points there ping the old gitterbot.... fixing it is not as simple as just changing the link tho because discord saves users based on an id rather than a username.. so we'll need to _also_ ping the discord API and get usernames to fill out the list.

**Comment by I3uckwheat** [comment]
@codyloyd Is this issue irrelevant now?

**Comment by I3uckwheat** [comment]
@codyloyd Thanks, i'll close this :)
