### ISSUE TITLE
Feature: Add command to display all available commands

### ISSUE THREAD

**Issue by arinze19** [TheOdinProject/odin-bot-v2#264]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `command name: brief description of request` format, e.g. `/help: add optional @user parameter`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

Add a command to let community members see a list of all available commands - `/commands-ls` | `!commands-ls`. This could foster better participation as users can see what commands are currently available and open PRs for commands they would love to see added.
New members to the server could have the bot send the command-list to their inbox so they get up to speed with how to use it.  

**2. Acceptance Criteria:**

**3. Additional Information:**

**Comment by Asartea** [comment]
Wouldn't the usecase for this (seeing what commands there are and how to use them) be at least partly solved by the changeover to slash commands, which easily allows a user to view the full list of commands + descriptions?

**Comment by arinze19** [comment]
Just read through the slash command docs. They would completely solve this use case. 
Guess all that's left is to migrate the existing commands to use slash commands

**Comment by ManonLef** [comment]
I will be closing this since it will be solved with the bot overhaul. Thanks again for the suggestion
