### ISSUE TITLE
modmail: Command to explain how to use modmail

### ISSUE THREAD

**Issue by crespire** [TheOdinProject/odin-bot-v2#281]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `command name: brief description of request` format, e.g. `/help: add optional @user parameter`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

Command should be `/modmail` and provide a brief description of how to use ModMail.

1. Some users have issues with messaging modmail due to their privacy settings, which we can prompt on.
2. Some users are not aware that modmail exists.

**2. Acceptance Criteria:**

A command with a response explaining modmail, and also prompting a user to check their DM permissions.

**3. Additional Information:**

**Comment by Iona01** [comment]
+ a note that if it doesn't work after they've checked their permissions on the Odin server, they may need to also allow Private Messages from any/all other discord servers that they share in common with the modmail bot - since this was my issue.

**Comment by ManonLef** [comment]
I actually wrote a modmail guide that resides in the #contact-moderators channel now [here](https://discord.com/channels/505093832157691914/1059513837197459547) 

Perhaps this could be useful. Just a quick brainstorm; if there were to be a modmail command, it could be a less detailed version that would link to the channel or the repo document for example.

Other possibilities: update faq to link to the channel containing the guide, make people aware of the guide in #contact-moderators when they ask. But I can see how not many people know of its existence yet.

**Comment by crespire** [comment]
Thanks for the input, Manon! I think that's very comprehensive already and I would only suggest adding additional info in the prompt that says "Why can't I send ModMail a message?" with some explanation.

If that can be updated, I don't think it's necessary to add a command, so I am going to close the issue.
