### ISSUE TITLE
/data: update wording to be more reflective of actual questions asked, and in line with /question command

### ISSUE THREAD

**Issue by ManonLef** [TheOdinProject/odin-bot-v2#283]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `command name: brief description of request` format, e.g. `/help: add optional @user parameter`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it (I couldn't find it in the commands folder though.

<hr>

**1. Description of the Feature Request:**

## Why?

The majority of the questions we see that get responded to with the `/data` command are questions that don't give away any information. The current `BAD` example contains more information than is usually given when responded to with `/data`. The current example could also be followed up with the `/question` command since we already at least now roughly what the issue is. I also think it would be better to make it more in line with the `/question` command because the current data output mentions nothing about 'what you've tried' for example. 

I think this command was implemented to avoid unnecessary back and forth because we'd prefer people to give as much info as possible up front so someone that actually knows how to answer will jump in instead of people having to pull out info only to find they can't help. 
Re: current `BAD` example; If someone sees this question and knows how to set CSS styles with javascript, they may just answer this with: `document.getElementById(id).style.property = new style` and the question asker may have actually gotten the answer they needed even though their question was in that case low effort and could have been googled. This makes the example bad in my opinion since this one actually could in some cases get satisfactorily answered even though it was googleable unless there was another problem like the script not being linked or other issues with the code.

Some recent examples of questions that were met with the `/data` command:
I edited these slightly because I don't want fellow learners to feel called out. Asking good questions and coming prepared is one of the things many still have to get used to and that's okay.

> Has anyone here had interviews for front end positions? 
- we have no idea what the student is going to ask about here besides the clue that it's in getting hired. However, someone might answer `yes` and get asked if they also needed to use the bathroom midway the interview (random example) and that person would have perhaps not answered if they knew this was the question. 

> is there anyone online, or should I wait?
- we have no idea what this student is about to ask about, we need more data. But often the one responding is the one they expect to help out, which leads to the responder having to send another message they can't help with that issue.

> Could anyone here help with my resume?
- that's what the channel is for. They are looking for confirmation. We also see variations of this a lot.

> Hi, anyone with linux skills around? I need help
- again, no idea what they need help with, could be setup, could be audio issues etc..

> Hi, I would love some help with my tic tac toe projects. I'd appreciate any help
- same as before, we have no idea. 

## Current output:
Instead of asking if anyone can help you, ask your question outright so people can help you!

Bad: "Hey, does anyone know how to set CSS styles with Javascript?"

Good:
"Hey, I'm having trouble setting CSS styles via Javascript.

Here's my code:
Code snippet

And here is the error I'm receiving:
Cannot set attribute 'style' of null "

https://www.dontasktoask.com/

## Proposed output

Instead of asking if anyone can help you, ask your question outright with as much information as possible so people will know if they can help you.

Bad: "Hey, anyone around that is really good with CSS?"

Good:
"Hey, I'm having trouble setting CSS styles via Javascript"

Project/Exercise:
Lesson link:
Code: [code sandbox like replit or codepen]
Issue/Problem: [screenshots if applicable]
What I expected:
What I've tried:

OR

Bad: "Hey, anyone around to help me real quick?"

Good:

"Hey, I'm having trouble setting CSS styles via Javascript"

Project/Exercise:
Lesson link:
Code: [code sandbox like replit or codepen]
Issue/Problem: [screenshots if applicable]
What I expected:
What I've tried:

https://www.dontasktoask.com/

**2. Acceptance Criteria:**

**3. Additional Information:**

**Comment by KevinMulhern** [comment]
Thanks for the detailed write up @ManonLef. Makes a lot of sense to me. Would it work with just the one example that doesn't give much information?

This one
```
Bad: "Hey, anyone around to help me real quick?"

Good:

"Hey, I'm having trouble setting CSS styles via Javascript"

Project/Exercise:
Lesson link:
Code: [code sandbox like replit or codepen]
Issue/Problem: [screenshots if applicable]
What I expected:
What I've tried:

https://www.dontasktoask.com/
```

If it's shorter/simpler, it might be read and taken onboard more. _But_... I'm admittedly not in chat and seeing the problems as often as you are. So whatever version you think will help most takes precedence.

**Comment by ManonLef** [comment]
Yes I did intend for picking one of those two :) I can see how that is not entirely clear with just my proposal containing `OR`

**Comment by KevinMulhern** [comment]
ahh gotcha, sorry I got my wires crossed lol. I'd vote for that version 😄 seems to be closest to the examples you posted.

**Comment by ManonLef** [comment]
No don't apologize, I should have definitely formatted that better! It looks like one message now. I'm  leaning towards a question with minimal but some info; 

> Someone around to help me with etch a sketch? 

Or 

> Hi, can I ask something about css? 

Or the first option I proposed

But I think they all convey the reality better compared to the current output, and adding the question template ups this command's effectiveness even more.
