### ISSUE TITLE
Feat: move to slash commands from text-based commands with exceptions

### ISSUE THREAD

**Issue by 01zulfi** [TheOdinProject/odin-bot-v2#297]
**1. Description of the Feature Request:**

As per discussion with the team, we would like the bot to default to slash commands. This means:

1. We'll move all of our text-based commands to slash
2. Any new commands will be slash 

Exceptions include:

1. Our points command is text-based, it doesn't need to be slash'ed
2. There are few commands that are useful in text context. Like !question, !code, and more. We need to have them duplicated over the slash command and text-based command.

This migration will also provide us with an opportunity to triage our commands where we can decide to improve or delete certain ones.

**2. Acceptance Criteria:**

- [ ] Build a system which allows command to be easily replicated for slash and text. It should allow us to use one source of truth for the command content.
- [ ] Migrate all text-based commands to slash except for our points giving command
- [ ] Remove text-based commands except for few (tbd)

**3. Additional Information:**

(putting this on hold as we figure out some particulars)

**Comment by ManonLef** [comment]
I'm sorry I missed this with the "on hold" tag. Here I am opening all those PR's. 
Are you okay with me going forward with the slash PR's since I have most lined up, or rather we wait? 

My reasoning being that we could filter some old commands out that aren't used (as discussed in the past) and update the to-be-converted ones while going through them since the legacy commands are all pretty basic. IT would be great if we could direct users to all commands in a glance typing just `/`.

I'd also be happy to write up a standard format or a short guide after that. 
Let me know how you'd like to proceed :)

**Comment by 01zulfi** [comment]
The idea behind this issue was to create a structure, or a class that could abstract text-based and slash commands into one. Something like: 
```js
class Command {
 regex = asdf;
 textCallback() { ... };
 slashCallback() { ... };
 content() { ... };
}
```
But there a bunch of edgecases we'd have to deal with. I haven't had a lot of time to think on this, and I also think it would just add unneeded complexity. 

@ManonLef Please go on with the slash conversion. We can always come back and refactor.

**Comment by Lofty-Brambles** [comment]
Is it open to work? I'm happy to create some backward compatible structures that work with it. If approved, I'll try a draft PR. @01zulfi

**Comment by ManonLef** [comment]
@Lofty-Brambles would you mind holding off for a bit? Most are actually already prepped by me or shipped or in PR status. Mainly because some needed a rewrite as well.

**Comment by wise-king-sullyman** [comment]
My understanding of the current plan is that the old text-based commands are all essentially going to be deprecated at the least (and not receive maintenance beyond critical bugfixes), is that correct?

**Comment by ManonLef** [comment]
@wise-king-sullyman my understanding is that most of them will not only be deprecated, but also be removed to reduce overhead of keeping slash and text-based in sync. 

A few of them will probably stay that are often used in a sentence.

**Comment by 01zulfi** [comment]
^ this. We will be removing all unnecessary text-based commands in favour of slash.

**Comment by wise-king-sullyman** [comment]
Whoops totally thought I followed up on this, my bad.

How many do we think will be staying text based?

**Comment by ManonLef** [comment]
I will be proposing a final overhaul soon. I think we will have 3 definite stays, and then the search commands on top of that (google, search top). This doesn't include the "listening commands" we have like @wise-king-sullyman ++

I have prepared most of the last command conversions and then I will propose the final bit, which is the removal of old text-based commands I think obsolete

**Comment by 01zulfi** [comment]
@ManonLef great work. I see now we have a bunch of text command files labeled with `-legacy`. Any reason for that?

**Comment by ManonLef** [comment]
@01zulfi from the top of my head (not near my computer) those are commands we now have in both slash form and the old/legacy style. The legacy ones are the ones prefaced with an exclamation mark. I think we settled on adding legacy to the naming to avoid confusion.
