### ISSUE TITLE
Fix: Re-work the getting started instructions

### ISSUE THREAD

**Issue by LeoKirasic** [TheOdinProject/odin-bot-v2#302]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `command name: brief description of request` format, e.g. `/help: add optional @user parameter`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

The current getting started instructions aren't up to date with how discord handles bots now. 

**2. Acceptance Criteria:**

Include instructions for discord guild id and discord client id. 

**3. Additional Information:**

**Comment by ManonLef** [comment]
@LeoKirasic per your request

**Comment by LeoKirasic** [comment]
@ManonLef assigned. Thanks for wanting to work on this!

**Comment by LeoKirasic** [comment]
New getting started instructions look great! Thanks @ManonLef
