### ISSUE TITLE
Bug - Question commands: contain dead link

### ISSUE THREAD

**Issue by Eduardo06sp** [TheOdinProject/odin-bot-v2#317]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - points command: Extra whitespace causes command to not be called`

The following checkbox is OPTIONAL:

-   [] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**
A clear and concise description of what the bug is. Include any screenshots that may help show the bug in action. -->
In the Discord, triggering the question command links to a small explanation about asking better questions. The link provided: https://www.theodinproject.com/how_to_ask

is dead. The good link is:
https://www.theodinproject.com/guides/community/how_to_ask

**2. How To Reproduce:**
What steps one might need to take in order to reproduce this bug, e.g.:
1. Open Discord
2. Go to the botspam channel
3. Type `!question` or `/question`
4. Click on the (dead) link from the auto-generated bot response

**3. Expected Behavior:**
A brief description of what you expected to happen, e.g.:
1. Open Discord
2. Go to the botspam channel
3. Type `!question` or `/question`
4. Click on the link successfully, which should take you to https://www.theodinproject.com/guides/community/how_to_ask

**Comment by CouchofTomato** [comment]
@TheOdinProject/odin-bot Can someone take a look at this please.

**Comment by wise-king-sullyman** [comment]
Seems like something that should get fixed, thanks for filing this @Eduardo06sp!

**Comment by Asartea** [comment]
Would be willing to tackle this

**Comment by CouchofTomato** [comment]
@Asartea All yours
