### ISSUE TITLE
Points: Consider allowing a single space between the mention and the ++ 

### ISSUE THREAD

**Issue by Asartea** [TheOdinProject/odin-bot-v2#352]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)

-   [x] The title of this issue follows the `command name: brief description of request` format, e.g. `/help: add optional @user parameter`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**
- Probably the single most often made mistake with the points command is people sending `@username ++` instead of `@username++`. I can't really think of an edgecase where we wouldn't want to trigger the give points behavior, and allowing it would solve a lot of confusion

**2. Acceptance Criteria:**
- [ ] adding a space between the username and the `++` / star also triggers the command

**Comment by manny53365** [comment]
I would be interested in working on this when given the green light

**Comment by Asartea** [comment]
This apparently already works; I have no clue why I filed this (but also I swear I've seen this gone wrong before)
