### ISSUE TITLE
/commands: Links to a writeup that holds commands list + small desc.

### ISSUE THREAD

**Issue by Baguirre03** [TheOdinProject/odin-bot-v2#374]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)

-   [x] The title of this issue follows the `command name: brief description of request` format, e.g. `/help: add optional @user parameter`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

I think that using `/commands` should send a link in the chat where there is a writeup including all of TOP's commands as well as a small description along side it. 

**2. Acceptance Criteria:**

- [ ] Decide where write-up is hosted and how it is formatted
- [ ] New-era command created that sends link to it

**3. Additional Information:**

**Comment by Baguirre03** [comment]
I _think_ that this could be easily automated, more specifically because most new commands have that title and description we could just use those. I will note having to scroll to find all odin-bot commands when using `/` may not be known by most people.

**Comment by ManonLef** [comment]
I agree, and that's why I think it would be nice to add that information to the help command (once that gets updated).
Having a huge list of available commands show up in chat doesn't feel exactly right either, but it could be made ephemeral I guess. 

Would love more opinions on this from @TheOdinProject/maintainers

**Comment by zachmmeyer** [comment]
I agree with @ManonLef, having a big list of commands show up in chat, hidden or not, does not feel right. As we migrate fully to slash commands it would only make sense to check using Discord's built in features. We can't really help people who don't know how to use Discord, and even then they'd have to know the command to show all the commands.
That is my personal two cents.

**Comment by Baguirre03** [comment]
Fair enough. 
Still, I like this from Manon and think it should be added :) :
> I agree, and that's why I think it would be nice to add that information (about all commands visible when typing /) to the help command (once that gets updated).

Sounds like `/commands` isnt needed though, closing this issue!

**Comment by ManonLef** [comment]
@Baguirre03 The help command will definitely be updated, currently working on quite a few bot updates actually
