### ISSUE TITLE
make tests & require them for new command additions

### ISSUE THREAD

**Issue by ryanford-dev** [TheOdinProject/odin-bot-v2#38]
Would help fight buggy regex issues

-----------

Briggs wrote the below:

- [x] Setup [jest](https://jestjs.io/) as a dev dependency
- [ ] Add unit tests for all commands
- [ ] Add unit tests for all helper functions that are public
- [ ] Add issues for any problems identified by the tests
- [x] Add a **pre-push** [git-hook](https://githooks.com/) to prevent pushing (there may be a lib to help with this)

The goals of these tests are to help prevent REGEX issues, as well as making sure the bot is solid. If you'd like to help with this, I'm organizing a team to do this. Please comment here if you'd like to be on the team!

**Comment by aplyd** [comment]
I'd love to help!

**Comment by twalton83** [comment]
Happy to join the team.

**Comment by ryanford-dev** [comment]
@I3uckwheat next time just make a child comment, don't edit the OP

**Comment by I3uckwheat** [comment]
@ryanford-dev I figured it wasn't' a big deal, as it literally just said: "Would help fight buggy regex issues"

**Comment by I3uckwheat** [comment]
@twalton83 Would you like to lead this?

**Comment by twalton83** [comment]
@I3uckwheat I don't mind! Only thing I don't know how to do is the git hook but I can look into it or see if someone else is familiar.

**Comment by dvik1950** [comment]
I'd like help implement the pre-push hook, I don't have any experience with git hooks but I hope it's not too complicated and the deadline isn't tomorrow or something lol

> Add a pre-push git-hook to prevent pushing (there may be a lib to help with this)

Another thing, I'm not entirely sure what's the purpose of such a hook

**Comment by I3uckwheat** [comment]
@dvik1950 The purpose of the git hook is to prevent pushing if there are any failing tests. The hook will run the tests before pushing and can stop a push before it happens when writing `git push origin <branch>`

@twalton83 Great! It looks like you have enough people interested to get started! So start when you're ready! I'm around if you need to ask anything :)

**Comment by twalton83** [comment]
@dvik1950 We made a private Discord channel for the issue, what’s your username?

**Comment by twalton83** [comment]
Dependency added here: https://github.com/TheOdinProject/odin-bot-v2/pull/63

**Comment by twalton83** [comment]
The commands themselves have been refactored, and there are now test files for every command, with an example in callbacks.test.js.
