### ISSUE TITLE
Multiple slash commands: Add optional user mention parameter

### ISSUE THREAD

**Issue by MaoShizhong** [TheOdinProject/odin-bot-v2#404]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)

-   [x] The title of this issue follows the `command name: brief description of request` format, e.g. `/help: add optional @user parameter`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**
Exactly like how `/google` and `/time` have optional user mention options, I feel most of the other commands would benefit from having that option as well, since for example unlike being able to type `@mao_sz !question` in one message, you'd have to `/question` then `@mao_sz` in a separate message (can get buried with fast-moving conversations).

**2. Acceptance Criteria:**
- [ ] Add optional `.addUserOption((option) => option.setName('user').setDescription('user to ping')),` to data properties
- [ ] Add `const userId = interaction.options.getUser('user')?.id;` to execute function and edit reply object

**3. Additional Information:**
N/A

**Comment by CouchofTomato** [comment]
@TheOdinProject/odin-bot 

Can somebody take a look please.

**Comment by ManonLef** [comment]
I agree this would be a good addition and will assign you.
