### ISSUE TITLE
No command name: Add The Office Club-40 gif to the collection of possible gifs

### ISSUE THREAD

**Issue by zachmmeyer** [TheOdinProject/odin-bot-v2#408]
Complete the following REQUIRED checkboxes:
-   [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)

-   [X] The title of this issue follows the `command name: brief description of request` format, e.g. `/help: add optional @user parameter`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

I saw this [sweet gif](https://media.tenor.com/VRYCq0ZeasQAAAAC/dundie-award.gif) that does not seem to have an author pop up in Club-40 and it is not in [collection of possible gifs](https://github.com/TheOdinProject/odin-bot-v2/blob/main/botCommands/club_40_gifs.json). I think it should be added!

**2. Acceptance Criteria:**

- [ ] Add the gif
- [ ] Set the author to "Unknown" (so hopefully they'll notice and add themselves later)

**3. Additional Information:**

Here is the page from Tenor: https://tenor.com/view/dundie-award-odin-club40-gif-20404923
The user is elrolamenton, but nobody on the server matches with that name.

**Comment by rishikumars-in** [comment]
Can I take this?

**Comment by zachmmeyer** [comment]
@rishikumars-in all yours

**Comment by JustWaveThings** [comment]
@rishikumars-in  reply here with your questions / concerns  :)

**Comment by rishikumars-in** [comment]
@JustWaveThings Thanks. I don't know where to start the work. Elaborate more & Guide me on how to add the specified GIF.

**Comment by zachmmeyer** [comment]
@rishikumars-in https://github.com/TheOdinProject/odin-bot-v2/blob/main/botCommands/club_40_gifs.json
I also updated the original issue to include that link. Does it help you sufficiently?

**Comment by rishikumars-in** [comment]
@zachmmeyer Thanks for your help. Added the gif and created pull request. Hope I did it in the right way. 😊

**Comment by zachmmeyer** [comment]
@rishikumars-in you did perfect.
