### ISSUE TITLE
!code: update the !code command to same formatting as /code slash command

### ISSUE THREAD

**Issue by ManonLef** [TheOdinProject/odin-bot-v2#411]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)

-   [x] The title of this issue follows the `command name: brief description of request` format, e.g. `/help: add optional @user parameter`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

update the `!code` command to the exact same formatting as the `/code` command has. This includes descriptive links

**2. Acceptance Criteria:**

- [ ] update title to sentence case "How to share your code"
- [ ] copy the body / main text from the `/code` slash command
- [ ] update snapshots

**3. Additional Information:**

This is probably one of the old commands that will remain available as non-slash

**Comment by CouchofTomato** [comment]
@TheOdinProject/odin-bot

**Comment by ManonLef** [comment]
I opened this issue hoping a contributor wanted to pick it up. If no-one does I'll be happy to add it myself :)

**Comment by CouchofTomato** [comment]
I wonder if learners won't see it because it's not one of the common repos to check for contribution opportunities.

**Comment by Asartea** [comment]
I mean, if nobody else wants it...

**Comment by ManonLef** [comment]
Thanks Asartea! I only saw this now while readying my PR.

**Comment by Asartea** [comment]
np
