### ISSUE TITLE
Rework /help command

### ISSUE THREAD

**Issue by Mclilzee** [TheOdinProject/odin-bot-v2#422]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)

-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - points command: Extra whitespace causes command to not be called`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

Currently, the `/help` command prints out information about the points system and `!leaderboard`. We moved away from `!leaderboard` command, and the current information is given about the points system is better covered in our current subcommand `/points info`.
Here is a side by side comparison :
![image](https://github.com/TheOdinProject/odin-bot-v2/assets/70924991/8caee942-8dc1-42cf-b1e0-5847e9b9e7b6)
![image](https://github.com/TheOdinProject/odin-bot-v2/assets/70924991/620f3d9d-af91-4091-9f7d-5ed55eba9c66)

A rework of `/help` is in order, to be more modern and concise with all the changes we have already been doing with the bot, moving away from it giving information about the points system to something more helpful for beginners. It can even have multiple subcommands we could squash together some of the other commands into it as well.

One possibility is to put a brief descriptions and introduction to how to use/discover the slash commands on the server, and some general information about the rules, channels or links to articles about them.

This issue is open for discussion of how to proceed.

**2. How To Reproduce:**

Use `/help` command on discord.

**Comment by JustWaveThings** [comment]
I am looking to contribute to the bot and am willing to mock something up for an improved `/help` command, based on the ideas above. 

Would that be ok?

**Comment by Mclilzee** [comment]
@JustWaveThings I believe that your question was for maintainers, but in case it was aimed at me, then of course yes, that would be a great idea, and thank you for wanting to take this on.

**Comment by JustWaveThings** [comment]
Thank you @Mclilzee! This was a good call-out. 

Sorry, I wasn't clear. I was looking for a maintainer's approval for a go-ahead.

**Comment by ManonLef** [comment]
Hi @JustWaveThings 

This is a great idea. I've assigned it to you. We already spoke about some ideas in discord and probably you have some thoughts of your own about it. Curious to see your ideas and what you decide on! 

We can discuss the changes further on the PR if/as needed.

**Comment by JustWaveThings** [comment]
https://discord.com/channels/505093832157691914/1154146232063770747/1155877694660161676 

Crossposting this from Discord.

So initial thoughts after some poking around. 

I think the help command could emulate the points command in structure. /help would bring up all the help options like /points does:

![image](https://github.com/TheOdinProject/odin-bot-v2/assets/48169481/c4f6daf7-f800-48f1-a3af-e1de75d86f17)


Making the help command like this would give it much more flexibility to include what the asker wants without having a large embed trying to cover all the bases.

To do this, I would emulate most of what is in points.service.js

I am going to wait for feedback though before going down this route.

I am going to cross-post this to the issue in the bot repo.

Open to thoughts/suggestions/things to watch out for, as always!

**Comment by Mclilzee** [comment]
This is a great idea, it's what I initially had in mind, our commands have been growing in numbers, and we need to start using sub commands more to keep it concise without adding too many related commands into the API.

Maybe look at our current commands and see what are available, that can be potential candidate to the subcommands of help too. For example, the command `/data` could be a potential candidate for `/help asking-questions` or `/help questions`

**Comment by JustWaveThings** [comment]
Just so it doesn't get lost, I've opened a PR that's ready for some more feedback in #450.

**Comment by MaoShizhong** [comment]
Just want to check if there's anything still further that might need doing for this issue?

**Comment by Mclilzee** [comment]
Looks like the PR has been merged, this issue should be safe to close. If however, something comes up that is related, we can just submit a new issue.
