### ISSUE TITLE
/support command's response button

### ISSUE THREAD

**Issue by Mclilzee** [TheOdinProject/odin-bot-v2#431]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)

-   [x] The title of this issue follows the `command name: brief description of request` format, e.g. `/help: add optional @user parameter`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

the `/support` command currently prints out a message with two buttons, one of which being the `💰 Donate Now`
I feel that this button emoji can be something more on the idea of what is it to support us. Because for me the money bag kind of resembles greed, maybe from all the cartoon that I watched when I was a kid that had greedy people having lots of money bags, or banks.

It could be an emoji of Open collective, Heart, custom-made emoji, or this rocket 🚀 I'm pretty sure there are better ideas too.

Appreciate a second opinion on this if someone can see the connection I'm making

**2. Acceptance Criteria:**

Replace money bag emoji with something else

**3. Additional Information:**

I left the assignment box unchecked in case this issue gets accepted, it would be a good first contribution

**Comment by 01zulfi** [comment]
@Mclilzee can't make the 💰 -> greedy connection personally, but happy to concede to another emoji. What do you think about 🚀 then?

**Comment by Mclilzee** [comment]
I don't feel this one represent the donation idea either, I think more opinion about this from the team would do us good here. Could be it's only me that sees it as greed emoji.

**Comment by MaoShizhong** [comment]
While I can see how some might think :moneybag: a bit of stretch for "greed", I can actually see how some would associate it slightly more that direction.
Like, I don't think it's a "big deal" by any means, but the suggestion does still make sense to me as to where it's coming from.

A custom emoji for Open Collective sounds nice. How about making the backer badge a custom emoji and using that instead? Don't think a coin, particularly one with Odin on it *and* the one that's used as the backer role badge, can be argued as "greed-related" as :moneybag:

Thoughts?

**Comment by BryanF1nes** [comment]
I'm not sure if this is still something being discussed, but I like the suggestion from Mao.

Something that is more related to Odin as a "brand" feels like a smarter option.

**Comment by MaoShizhong** [comment]
@Mclilzee happy to change the emoji for the donate button to use `'1270559118368964710'`? That's the backer coin emoji ID number

**Comment by Mclilzee** [comment]
Yes, that is very reasonable and a great idea!

**Comment by MaoShizhong** [comment]
## Acceptance criteria

- [ ] The `/support` slash command's "donate" button has its emoji changed from `'💰'` to `'1270559118368964710'`

Please comment below if you'd like to be assigned to this issue. Please do not open a PR unless you have been assigned by a maintainer.

**Comment by ItsTosh** [comment]
Hey 👋 I would like to contribute if possible. 

Just for clarification as well, all you need to do is change `.setEmoji('💰')` in 
https://github.com/TheOdinProject/odin-bot-v2/blob/9ced2805a0bbd2737f493860e114ab942f37e47e/new-era-commands/slash/support.js to match `'1270559118368964710'`?

**Comment by MaoShizhong** [comment]
@ItsTosh just `.setEmoji('1270559118368964710>')` should be sufficient.
