### ISSUE TITLE
Bug - Bot cuts off FAQ sentences mid-word

### ISSUE THREAD

**Issue by ManonLef** [TheOdinProject/odin-bot-v2#456]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)

-   [x] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - points command: Extra whitespace causes command to not be called`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

![Screenshot 2023-10-15 at 11 25 00](https://github.com/TheOdinProject/odin-bot-v2/assets/81025586/0437bee3-0a79-4be7-b4da-a0cbd3feee99)

The bot is cutting off words. MD parsing method should probably be updated. 

**2. How To Reproduce:**

1. Log in to discord
2. Navigate to [FAQ](https://discord.com/channels/505093832157691914/823266307293839401/1162908825091842119)
3. Behold the last and first "word" of the first and second bot message respectively. 

**3. Expected Behavior:**

Cut off should happen by section preferably.

**Comment by Asartea** [comment]
Could I be assigned this?

**Comment by ManonLef** [comment]
All yours @Asartea !

**Comment by Asartea** [comment]
Am currently a bit too busy I'm afraid for this
