### ISSUE TITLE
/multiplecourses - command to address questions about supplementing top concurrently

### ISSUE THREAD

**Issue by JustWaveThings** [TheOdinProject/odin-bot-v2#462]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)

-   [x] The title of this issue follows the `command name: brief description of request` format, e.g. `/help: add optional @user parameter`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

Feature:
- Slash command /multiplecourses that contain Briggs's advice about the topic.

Benefit:
- Reduce friction to provide learners with what TOP recommends regarding topic
- Learners get consistent messaging.

Solves:
- Having to search for a pinned message, or taking the time to type out a response in the moment that paraphrases the advice contained in the pin.
- Less workload for those involved in moderating or even helping out in chat.

**2. Acceptance Criteria:**

- [ ] /multiplecourses typed in textbox would bring up the command
- [ ] Optional ability to tag a user 
- [ ] Contains the content:
https://discord.com/channels/505093832157691914/505093832157691916/778727680438698055 
https://discord.com/channels/505093832157691914/505093832157691916/778727683675914300
https://discord.com/channels/505093832157691914/505093832157691916/778728005904105512
(perhaps edited for brevity)

**3. Additional Information:**

Open to a different command name. It's just what came to me.

**Comment by ManonLef** [comment]
I was thinking about the name `/tutorialHell` but that might be too much :D

Great idea Fred

**Comment by JustWaveThings** [comment]
/tutorialHell  :chefkiss:  

I mean in all seriousness, that might be a good name.
