### ISSUE TITLE
/stuck: Command that shows diagram for when people query about the best "I'm stuck" workflow 

### ISSUE THREAD

**Issue by MaoShizhong** [TheOdinProject/odin-bot-v2#466]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)

-   [x] The title of this issue follows the `command name: brief description of request` format, e.g. `/help: add optional @user parameter`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**
It's quite common for people to ask questions about or in some way express frustration that highlights or raises suspicion about less-than-ideal learning habits and expectations during exercises/projects. Quite commonly they'll be along the lines of not "fully understanding" everything after reading a lesson, or feeling like they did but as soon as they got to a project it's out the other ear already, not revisiting past lessons, or something that hints at them reluctant to ask for help/thinking asking for help should only ever be a last resort and they should struggle alone as long as is possible first.

@bycdiaz drew up a [very neat little diagram](https://discord.com/channels/505093832157691914/505093832157691916/1165743696176758824) the other day which I think (perhaps along with a brief text-version), would be really useful to put in an embed callable by `/stuck` or some equivalent/better name. It should help streamline and make giving advice for this a little more consistent.
Maybe also add the link to AI and learning at the very bottom of it just mentioning the dangers there.

**2. Acceptance Criteria:**
A list of checkbox items that explain the requirements needed to be met to resolve this request, e.g.:
- [ ] Typing `/stuck` will bring up the slash command in Discord
- [ ] Optional user mention option
- [ ] Bot embed contains [this image](https://cdn.discordapp.com/attachments/505093832157691916/1165743695946068168/task-workflow.png?ex=6547f66b&is=6535816b&hm=6eb6cfeab91e9bde824735cab174ee4d7f921e84742f87f627c33190069b04db&)
- [ ] (Optional) includes text version of the flow chart (e.g. 1. ... 2.... 2.1 ..go to step 3   etc.)
- [ ] Mentions negative impact of using AI during learning with a link to https://www.theodinproject.com/lessons/foundations-motivation-and-mindset#a-note-on-ai-code-generation like with the `/ai` command

**Comment by ManonLef** [comment]
Sounds wonderful Mao! I'd love to hear the copyright holder's thoughts @bycdiaz on this as well 😄. 

I am of the opinion it could be useful to add a note on the `/question` template command because many people will end up asking a question when stuck. Could you expand on your motivation for including note of the `/ai` command?

**Comment by bycdiaz** [comment]
I wouldn't object to including the diagram at all :)

**Comment by MaoShizhong** [comment]
If this does go ahead, would the preferred way to handle the image be by uploading it elsewhere then linking the URL in the command embed? Or by using the attachment builder which will upload the image using a local file directly?

**Comment by MaoShizhong** [comment]
Gentle bump 
Had *a lot* of cases over the last few months where I've linked the workflow message/image which has shown to be really helpful.

**Comment by MaoShizhong** [comment]
@bycdiaz @CouchofTomato Just wanted to clarify if the assignment to Carlos was intended/means the idea is approved and he's been asked to work on implementing this.

Based on [his reaction on Discord](https://discord.com/channels/505093832157691914/505093832157691916/1209899399640260688), there may or may not have been a miscommunication?

**Comment by 01zulfi** [comment]
@MaoShizhong, like the idea, you're assigned.
