### ISSUE TITLE
Channel that includes messages that have been bookmarked a certain number of times

### ISSUE THREAD

**Issue by nikitarevenco** [TheOdinProject/odin-bot-v2#492]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)

-   [x] The title of this issue follows the `command name: brief description of request` format, e.g. `/help: add optional @user parameter`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

When I bookmark a message with 📖 I do it because I want to refer to this information at a later date. However, I think it would also be very useful to have a list of useful/helpful messages that other people found helpful. So for example, if some message receives 3x 📖 it probably means that this message has some value / importance to several people and this message could be included in this new channel. let me know what you think about this! 

All of this will be automatic with the odin bot.

**2. Acceptance Criteria:**

- [ ] A new discord channel called something like `bookmarked` (we can decide on a better name)
- [ ] When a message receives the 📖 emoji, the bot checks if the message now has `3` (could be less could be more) book emojis.
- [ ] If it does, the bot will send the message not only to the user that bookmarked the message, but also send it in the new `#bookmarked` channel in the same exact format as it sends the message to the user (So it'll include a `jump to message` for example)

**3. Additional Information:**

Discord name: Revenco
I've made this suggestion in the `#discord-suggestion` channel and was redirected here. ([link to suggestion](https://discord.com/channels/505093832157691914/1209640025529122886))
I'm happy to work on this feature, although I think a channel in the discord would need to be created for me to be able to test it

**Comment by 01zulfi** [comment]
@nikitarevenco Thanks for creating this issue. I have some thoughts, but let's discuss with the team first.

@TheOdinProject/moderators @TheOdinProject/maintainers what do y'all think?

**Comment by thatblindgeye** [comment]
I'm a bit out of touch with the channels so take my opinion with a grain of salt 😆 

But I'm not sure if it'd be worth adding more bloat to the hefty amount of channels we already have. Another issue would be the number of bookmarks that are required, as it's difficult to really decide what the "right" number is. Is 10 bookmarks enough? Would 20 be too many based on the average amount of bookmarks a single post gets?

Finally, what people find useful to bookmark can vary *wildly*, and such a channel could become extremely bloated depending how often the bookmark feature is being used. At a certain point it could become difficult to sift through all of the bookmarks to see what the person finds useful.

That said, I also wouldn't be opposed to this feature. Mainly just want to mention some potential issues, but if overall the benefit is significant and outweighs any downside I wouldn't block it.

**Comment by MaoShizhong** [comment]
From my own experiences across the channels, even some of the most helpful messages don't get a great deal of bookmarks. Generally stuff that gets bookmarked are things sent during 1:1 help and so often only get 1 or 2 bookmarks.

Even the few times something might get something like 3-6 bookmarks, it's actually quite often something that's already been bookmarked several times a previous time it was posted, just by different people (or people like me with terrible memory and bookmark anyway just in case).
Which also means that stuff that gets multi-bookmarked will be more likely to be reposted for someone else's situation in the future. So this naturally increases awareness of it already. And those *super* helpful resources that address a hole in the curriculum often end up getting added to the curriculum in some capacity anyway.

So I'm not so sure that a feature like this would be the most feasible because:
- As above, how do we decide the threshold?
- As above, bloating over time
- What about if and inevitably *when* the same content surpasses whatever bookmark threshold just in a different post? I can see such a channel being filled with multiple of the same content further adding to bloat.

**Comment by nikitarevenco** [comment]
> From my own experiences across the channels, even some of the most helpful messages don't get a great deal of bookmarks. Generally stuff that gets bookmarked are things sent during 1:1 help and so often only get 1 or 2 bookmarks.
> 
> Even the few times something might get something like 3-6 bookmarks, it's actually quite often something that's already been bookmarked several times a previous time it was posted, just by different people (or people like me with terrible memory and bookmark anyway just in case). Which also means that stuff that gets multi-bookmarked will be more likely to be reposted for someone else's situation in the future. So this naturally increases awareness of it already. And those _super_ helpful resources that address a hole in the curriculum often end up getting added to the curriculum in some capacity anyway.
> 
> So I'm not so sure that a feature like this would be the most feasible/valuable because:
> 
> * As above, how do we decide the threshold?
> * As above, bloating over time
> * What about if and inevitably _when_ the same content surpasses whatever bookmark threshold just in a different post? I can see such a channel being filled with multiple of the same content further adding to bloat.

> * As above, how do we decide the threshold?
> * As above, bloating over time

I think 3 bookmarks is the perfect threshold for something like this. Reasoning:
- During 1-on-1 help, it is quite often that a message will be bookmarked with a single bookmark. So there must be significantly more messages with 1 bookmark than there are with 2 or more, and messages with 1 bookmark are more likely to only be relevant to whoever bookmarked that message rather than being generally useful
- I would assume that if a message has been bookmarked by 2 or more people, then it is generally useful. 3 bookmarks even further increases the odds that the message is very useful
- It doesn't necessarily mean that a message with 4 bookmarks is necessarily more helpful than the one with 2 bookmarks. For example, a helpful message regarding HTML/CSS has more "reach" than a helpful message regarding Express.js.

> * What about if and inevitably _when_ the same content surpasses whatever bookmark threshold just in a different post? I can see such a channel being filled with multiple of the same content further adding to bloat.

That makes sense, but no single person is going to browse through the entire channel. Maybe people are at most going to browse through the most recent 15-30 posts. It is therefore unlikely that there would be many messages in that range that repeat

To further make the channel more searchable, every post can have whatever channel the message originated from. For example, if a message originates from React-help channel, then the bot will mention that, which will let people specifically search for "#react-help" in this bookmark channel to filter only the content they'd want to see

**Comment by MaoShizhong** [comment]
Going to close this as it seems we're not intending to implement this for the above reasons.
