### ISSUE TITLE
Slash commands: Group several similar commands into single commands

### ISSUE THREAD

**Issue by cakegod** [TheOdinProject/odin-bot-v2#512]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)

-   [x] The title of this issue follows the `command name: brief description of request` format, e.g. `/help: add optional @user parameter`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

Several similar commands can be grouped into single commands. For instance, we currently have the following commands to search in a specific site:
- `/google` to search in google
- `/searchmdn` to search in MDN docs
- `/searchtop` to search in TOP

~~I suggest we group those commands into a single command `search` with the `site` as an option. The `site` option would contain a dropdown containing the site the user wants to search in.~~

I suggest we group those commands into a single command, with each site as a subcommand.

**2. Acceptance Criteria:**

- [ ] All slash commands that can be grouped are grouped into single commands

**3. Additional Information:**

**Comment by JustWaveThings** [comment]
https://discord.com/channels/505093832157691914/514204569572605952/1217905663389204631  Discord conversation here for context

**Comment by MaoShizhong** [comment]
I like this idea, especially since it'll make it easier for people to remember/become aware of the other search commands. 
I'm going to assume you also intend to have a `prompt` option and that you just forgot to include it in the issue?

@TheOdinProject/odin-bot thoughts?

**Comment by cakegod** [comment]
The `prompt` and `user` options that we use in the multiple search commands will be included.

**Comment by cakegod** [comment]
After [discussing](https://discord.com/channels/505093832157691914/514204569572605952/1217953201547116669) with @MaoShizhong. I've changed my approach to use subcommands instead of a `site` option with a list of site choices. This allows the user to quickly autocomplete the command to the site they want to search. 

For example, instead of autocompleting to `/search` and then selecting the site option, we can directly write `/go` and autocomplete to `/search google`. This reduces the number of steps, improving the user experience.

**Comment by 01zulfi** [comment]
@cakegod Thanks for opening the issue. Grouping search commands was already in the pipeline, but I never got around to actually following through.

Do ping whenever the PR is ready for review
