### ISSUE TITLE
Wiki page Commands contains outdated info

### ISSUE THREAD

**Issue by Asartea** [TheOdinProject/odin-bot-v2#525]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description:**
The [Commands wiki page](https://github.com/TheOdinProject/odin-bot-v2/wiki/Commands) contains several pieces of outdated info regarding how commands work:
1. It still refers to the old way of using text-based commands and `registerBotCommand()`, whereas nowadays most commands should be slash commands only
2. It mentions TOP uses v11 of DiscordJS; we are up to v14 these days

**5. Additional Information:**
As this is a wiki page it will need a maintainer to make changes

**Comment by CouchofTomato** [comment]
@TheOdinProject/odin-bot Can someone take a look at this please

**Comment by MaoShizhong** [comment]
Thanks for raising this, @Asartea. I've updated the [Commands wiki page](https://github.com/TheOdinProject/odin-bot-v2/wiki/Commands) - let me know if this looks okay.

**Comment by Asartea** [comment]
LGTM, thanks @MaoShizhong
