### ISSUE TITLE
OS: Add link to list of reasons why TOP doesn't support Windows?

### ISSUE THREAD

**Issue by Asartea** [TheOdinProject/odin-bot-v2#547]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)

-   [x] The title of this issue follows the `command name: brief description of request` format, e.g. `/help: add optional @user parameter`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**
Currently, the OS command states that TOP doesn't support Windows, but doesn't give any concrete reasons for it. There is a list however on Discord of reasons [why TOP doesn't support Windows](https://discord.com/channels/505093832157691914/690588860085960734/828714982253789215), which is the same message that gets linked at the top of the FAQ. While `(!|/)os` is meant to be operating system agnostic, most questions still revolve around Windows, and I think it would be beneficial to add a link to that message to that command, in the form of something like this:

> [Windows](https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/installation-overview#os-options)
The Odin Project does not support Windows or any other OS outside of our recommendations. We are happy to assist with any questions about installing a VM, using WSL, or dual booting Linux.

> There is a [list of reasons why we don't support Windows specifically](https://discord.com/channels/505093832157691914/690588860085960734/828714982253789215)

> https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/installation-overview#os-options

**2. Acceptance Criteria:**
- [ ] A link to the message is included

**3. Additional Information:**

**Comment by ManonLef** [comment]
I agree this could be worded better. I also think that the main reasons for not supporting windows should be stated in the lesson linked.

We could also perhaps consider something along the lines of:

> The Odin Project does not support Windows or any other OS outside of our recommendations. To read more about the reasons why we don't support Windows and for guidance on how to set up your Windows machine for TOP we have made this lesson (link). 

Or something along the above lines. And then:

> In this Discord we also welcome any questions about installing a VM, using WSL, or dual booting Linux.

What would you think about that? I'd also appreciate some @TheOdinProject/moderators feedback here

**Comment by ManonLef** [comment]
Awesome, might be worth a check to see if you think the lesson is lacking.

**Comment by JustWaveThings** [comment]
@Asartea, here is a link to a blog post that Rachel made from Briggs's Discord posts - https://github.com/TheOdinProject/blog/wiki/Why-We-Do-Not-Support-Windows.  This could be easy to add to the curriculum.


As for the command, I'd be fine with adding the link to the `/os` command.

Something like:

> The Odin Project does not support Windows or any other OS outside of our recommendations. We are happy to assist with any questions about installing a VM, using WSL, or dual booting Linux. https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/installation-overview#os-options

> For more, check out this exhaustive list on ['Why we do not support Windows'](https://github.com/TheOdinProject/blog/wiki/Why-We-Do-Not-Support-Windows).
