### ISSUE TITLE
Provide Documentation on How to Set the Bot Up and Get it Running

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/odin-bot-v2#56]
* Creating the .env file
* How to set up a discord bot and where to get API keys - https://github.com/SinisterRectus/Discordia/wiki/Setting-up-a-Discord-application
* What commands to use to start it
* etc

**Comment by twalton83** [comment]
I just had this thought yesterday when setting it up. Luckily I already knew how to work with Discord bots, but it doesn’t hurt to lower the barrier of entry for others. If you weren’t working on this, I’m happy to do this.

**Comment by I3uckwheat** [comment]
@twalton83 I'll assign this to you :)

**Comment by twalton83** [comment]
We can close this one now :)
