### ISSUE TITLE
CircleCI: Add a test to run prettier

### ISSUE THREAD

**Issue by Asartea** [TheOdinProject/odin-bot-v2#560]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)

-   [x] The title of this issue follows the `command name: brief description of request` format, e.g. `/help: add optional @user parameter`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**
We've added prettier, but aren't currently checking if an file actually complies with it. Specifically, I think it would make sense to split the current `test-and-linters` into a new `tests` (which runs jest) and a `linters` (which runs eslint and prettier)

**2. Acceptance Criteria:**
- [ ] CircleCI runs prettier

**3. Additional Information:**

**Comment by Asartea** [comment]
Was playing around with this locally, and this has one major disadvantage: we will almost certainly end up with something that looks like `prettier --check .` which will check every file, which means it will fail until all of the files meet the prettier criteria. Running locally suggests that there are currently ~85 files with formatting issues.
I see two ways to deal with this: we can wait/ignore failure results until every old file is updated or we can bite the bullet and change all of them, with the understanding that this will almost certainly merge conflict with every outstanding PR. (the third option would be to find a way to run prettier only for changed files, but a quick search didn't reveal anything to me)

**Comment by MaoShizhong** [comment]
This one can be done via a separate GH action [creyD/prettier_action@v4.3](https://github.com/creyD/prettier_action) and adapting the markdownlint workflow from the curriculum repo for changed files, i.e. not using CircleCI. Got that working locally and it only checks changed files, correctly reporting only the ones that fail the `prettier --check` run.

I'm happy to throw in a PR for this, but if you really want to give this a go yourself, you can certainly do so.

**Comment by Asartea** [comment]
Ah, of course, that would work. It will be slightly awkward having one thing not being on CircleCi, but it's still fine. Am fine with you doing it; am also fine with doing it myself

**Comment by MaoShizhong** [comment]
Since I got one up and running then, I'll throw the PR in but your review would be welcome :+1:
I couldn't find a way through circleci docs to only run Prettier on changed files, only to run a prettier command if certain files had been changed.

**Comment by Asartea** [comment]
> 
Since I got one up and running then, I'll throw the PR in but your review would be welcome 👍
I couldn't find a way through circleci docs to only run Prettier on changed files, only to run a prettier command if certain files had been changed.

Same. I did look into if you could maybe do something funky with [prettier --cache](https://prettier.io/docs/en/cli.html#--cache), but I couldn't quite figure out how to persist those caches

**Comment by Asartea** [comment]
Also, while doing this I got into that old hard drug that is bash scripting, and this might be useful for somebody else: automatically run prettier for every file changed on the current branch when compared to `main`

```sh
changed_files=$(git diff --name-status main)

for file in $changed_files; do
  mode=$(echo "$file" | cut -f1)
  filePath=$(echo "$file" | cut -f2)
  if [ "$mode" = "M" ] || [ "$mode" = "A" ] || [ "$mode" = "AM" ]; then
    npx prettier --write --glob '*.js'
  fi
done
```
