### ISSUE TITLE
Enhancement - Document .env configuration and pre-requisite installs 

### ISSUE THREAD

**Issue by developersteve** [TheOdinProject/odin-bot-v2#564]
Complete the following REQUIRED checkboxes:
-   [ x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)

-   [ x ] The title of this issue follows the `Bug - location of bug: brief description of bug` format, e.g. `Bug - points command: Extra whitespace causes command to not be called`

Some steps are missing from the getting started documentation when deploying bot including the requirement to install `redis`, and possibly other pre-requisite installations for a successful odin-bot-v2 deployment. Without these installations, it will cause errors to occur related to the `REDIS_URL=redis://localhost:6379` line within the env config. 

Additionally, it looks like there are some missing configurational `.env` elements, including some admin-related features as outlined in the [config.js](https://github.com/TheOdinProject/odin-bot-v2/blob/db77cfc1a7933ab038f8e501d9c8f0bff421c836/config.js#L5) file

**Comment by developersteve** [comment]
Additionally Ive just discovered the `https://www.theodinproject.com/api/points` api call using the undocumented `.env` var for the `pointsbot_token`. 

Is there any particular format for the schema on that API so it can be replicated elsewhere, ideally locally?

**Comment by MaoShizhong** [comment]
Thanks for catching that, @developersteve. I've added the redis installation pre-req to the wiki, which should be the only missing pre-req to actually get the bot up and running locally.

@01zulfi do you know more about the points bot mentioned above? And do we also actually need the #getting-hired channel ID as an env variable and not hardcoded into `config.js` like with the other channel IDs? Since that seems to be the only time it's used.

**Comment by 01zulfi** [comment]
@MaoShizhong thanks for adding Redis on wiki. 

Points bot token is required for the bot to successfully create points on the site's db. afaik there's only a production token available. Let me ask the team if there's a dev version of the token available. 

And as far as the getting hired channel id, I agree it shouldn't be a env var. Let me fix this.

**Comment by MaoShizhong** [comment]
The bot dev token issue is superseded by #581 and the other issues have been addressed - will close this issue.
