### ISSUE TITLE
Abstract out isAdmin check to new utility in /utils

### ISSUE THREAD

**Issue by Asartea** [TheOdinProject/odin-bot-v2#566]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)

<s>-   [ ] The title of this issue follows the `command name: brief description of request` format, e.g. `/help: add optional @user parameter`</s>

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**
We currently duplicate the code for checking if an user is an "admin" in a number of places using roughly this snippet[1]
```js
      authorMember.roles.cache.forEach((value) => {
        if (config.roles.adminRolesName.includes(value.name)) {
          isAdmin = true;
        }
      });
```

this duplicates code, and also can be simplified to
```js
const isAdmin = member.roles.cache.some((role) => roles.adminRolesName.includes(role.name))
```

It would be beneficial to abstract this functionality out to a new `is-admin.js` file in `/utils`

[1] Taken from `points.js`

**2. Acceptance Criteria:**
- [ ] There is an utility function which checks if an member is an admin
- [ ] All code that needs to check this uses the utility function

**Comment by MaoShizhong** [comment]
We can certainly extract out the logic for `isAdmin` to a util function. Can just pass in the member so we have like `let isAdminMessage = isAdmin(message.member)` and `let isAdminUser = isAdmin(authorMember)` or equivalent.
