### ISSUE TITLE
/ai Language about The Odin Project discord Not being a place to double check ChatGPT output

### ISSUE THREAD

**Issue by bycdiaz** [TheOdinProject/odin-bot-v2#585]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)

-   [x] The title of this issue follows the `command name: brief description of request` format, e.g. `/help: add optional @user parameter`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

We have users arriving the to Discord server requesting that people examine output from tools like Chat GPT. We should avoid letting the Discord server becoming a place where people come to have their use of ChatGPT examined. 

**2. Acceptance Criteria:**

**3. Additional Information:**

A tiny blurb on the `/ai` server command that makes users aware that they shouldn't use our Discord server as a place to have their ChatGPT output examined for correctness.

**Comment by JustWaveThings** [comment]
I'll take this one!

**Comment by bycdiaz** [comment]
The real MVP.

**Comment by MaoShizhong** [comment]
*Do it.*
