### ISSUE TITLE
Feat: Replace issue templates with issue forms

### ISSUE THREAD

**Issue by Asartea** [TheOdinProject/odin-bot-v2#595]
Complete the following REQUIRED checkboxes:

- [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [x] The title of this issue follows the `command name: brief description of request` format, e.g. `/help: add optional @user parameter`

The following checkbox is OPTIONAL:

- [x] I would like to be assigned this issue to work on it

---

## 1. Description of the Feature Request

The current issue templates use GitHub's issue template syntax, which requires the contributor to wade through the underlying markdown, and means all instructions have to be written in markdown comments. GitHub also has an alternative syntax [issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms). These offer a few advantages when compared to issue forms:

- They make a clear distinction between "content" (stuff that should end up in the issue) and "guidance" (description of what to fill in), which makes both longer descriptions possible and means a contributor doesn't have to work through a long paragraph of commented out markdown
  - Because of this, links are also shown as actual links, meaning they are clickable without going to preview
- They allow for a clear specification of which fields exist, what type those fields are, which are required and which aren't, etc. This makes it much easier to ensure all necessary fields get filled in
- These already get used in several TOP repos, including curriculum and the website repo

## 2. Acceptance Criteria:

- [ ] The existing issue templates are converted to issue forms

## 3. Additional Information:

Another potential benefit would be to automatically create tasklists for acceptance criteria. This ought to be _theoretically_ possible using a slight abuse of the render syntax, but for some reason (??????) I seem to be only able to create tasklists in org repos, not my own (_grumbles_)

**Comment by MaoShizhong** [comment]
I like this idea. Neater and just all round easier to work with.
