### ISSUE TITLE
Add /debug command

### ISSUE THREAD

**Issue by aayushmau5** [TheOdinProject/odin-bot-v2#69]
Most people tend to skip over the debugging part and ask questions that can be solved by themselves if they knew how to debug. 

`/debug` should send a link: https://developers.google.com/web/tools/chrome-devtools/javascript

**Comment by twalton83** [comment]
Just now getting back to this, I'm not opposed. If you'd like, you can make the PR.

**Comment by aayushmau5** [comment]
Okay, Will make a PR on this. Thanks @twalton83
