### ISSUE TITLE
Add ESLint dependency

### ISSUE THREAD

**Issue by twalton83** [TheOdinProject/odin-bot-v2#71]
- We should add ESLint as a dependency with the same rules as the [theodinproject](https://github.com/TheOdinProject/theodinproject) repo in order to remain consistent.

Completion criteria:
- [ ] Setup ESLint
- [ ] use AirBnB rules
- [ ] setup pre-push hook to check eslint for issues before pushing

**Comment by dvik1950** [comment]
I'd like to work on this, if that's ok

**Comment by I3uckwheat** [comment]
@dvik1950 Awesome, thanks a lot bro!

**Comment by twalton83** [comment]
@dvik1950 Hi Viktor, was a PR ever made for this?

**Comment by I3uckwheat** [comment]
Yes, I took care of it. Thanks for reminding me about the issue @twalton83
