### ISSUE TITLE
Investigate possibility of automatically removing embeds when sending links through bot

### ISSUE THREAD

**Issue by I3uckwheat** [TheOdinProject/odin-bot-v2#86]
![image](https://user-images.githubusercontent.com/4411701/105189424-2f795b80-5af2-11eb-9036-f70246e4d06e.png)

This embed from medium is pretty annoying, it would be nice to have it automatically removed when we're sending links through the bot. 

This issue is to just research to see if this is possible by digging into the Discord API

**Comment by DaeguDude** [comment]
Are we looking for a solution that disable all the embed of the links that were sent through the bot?

I've looked up the solution to disable specific link, by wrapping them with `<link>`.

**Before**
<img width="1134" alt="Screen Shot 2021-01-23 at 12 13 05 PM" src="https://user-images.githubusercontent.com/35420073/105567322-95751580-5d74-11eb-9ecb-19bcbf59dec3.png">

**After**
<img width="1112" alt="Screen Shot 2021-01-23 at 12 14 02 PM" src="https://user-images.githubusercontent.com/35420073/105567325-9ad26000-5d74-11eb-9486-5be5eced515a.png">

Not too sure if this is the solution that you want though. 

More information can be found [here - how do I disable auto-embed](https://support.discord.com/hc/en-us/articles/206342858--How-do-I-disable-auto-embed-)

**Comment by I3uckwheat** [comment]
@DaeguDude I think you've solved it! Great work!

**Comment by DaeguDude** [comment]
@I3uckwheat No worries :) 

If there's a list of commands that we don't want the embeds on I'm happy to work on it to change accordingly

**Comment by I3uckwheat** [comment]
@DaeguDude Please make issues for them first, you may assign yourself, but lets spread some work out to give other's opportunities :)
