### ISSUE TITLE
/callbacks command should be its own word/group

### ISSUE THREAD

**Issue by twalton83** [TheOdinProject/odin-bot-v2#88]
The regex for this command currently fails our standards for our already-implemented tests. We need this command's string to only be triggered if the word itself is used in a message, otherwise it will accidentally be triggered by unrelated messages in the chat. 

An example of a regex that passes all of the necessary test is our [ /notes command ](https://github.com/TheOdinProject/odin-bot-v2/blob/master/botCommands/notes.js). 

Once you begin fixing the regex, you may ensure the regex passes all necessary requirements by running `npm test commandName.test.js` in the terminal. A **passing** output will look like this:

<img width="854" alt="Screen Shot 2021-01-22 at 9 08 20 AM" src="https://user-images.githubusercontent.com/22967723/105553050-b298de00-5cb9-11eb-86f1-00e60ca8a4cd.png">

Once you have a passing regex, our pre-push hook will not allow you to push your commit because the other commands currently do not pass their respective tests. To circumvent our pre-push hook, please push your changes using `git push --no-verify`, then make your pull request. 

**ACCEPTANCE CRITERIA**:
- [ ] The fixed regex passes all regex-related tests 
- [ ] The snapshot tests all pass and are not made obsolete by the new regex

**Comment by DaeguDude** [comment]
If other commands should be worked on(That other people are not working on), Could I take a swing?

**Comment by twalton83** [comment]
Please do, thank you!

**Comment by DaeguDude** [comment]
Cool! I've just finished `cqg` and `callbacks` command. However, while I'm working on `time` and `shrug` commands, they both have the issue regarding some TypeError.

It says `generateMentions` from 'mockData.js' is not a function. Here's how it looks like.
![Screen Shot 2021-01-25 at 10 07 20 AM](https://user-images.githubusercontent.com/35420073/105650001-997c7100-5ef5-11eb-8402-acc163047e88.png)

**Comment by twalton83** [comment]
Look at the mockData file and amend how generateMentions needs to be imported :D

**Comment by DaeguDude** [comment]
Oops, thought I shouldn't be touching anything other than regex commands :) Will do!

**Comment by twalton83** [comment]
No worries, you need to just change the import statement in the test file. The mockData file used to only have one function, now it exports two, so the import statement needs to adjust a bit.
