### ISSUE TITLE
/mv should be its own word or group

### ISSUE THREAD

**Issue by twalton83** [TheOdinProject/odin-bot-v2#91]
The regex for this command currently fails our standards for our already-implemented tests. We need this command's string to only be triggered if the word itself is used in a message, otherwise it will accidentally be triggered by unrelated messages in the chat. 

An example of a regex that passes all of the necessary test is our [ /notes command ](https://github.com/TheOdinProject/odin-bot-v2/blob/master/botCommands/notes.js). 

Once you begin fixing the regex, you may ensure the regex passes all necessary requirements by running `npm test commandName.test.js` in the terminal. A **passing** output will look like this:

<img width="854" alt="Screen Shot 2021-01-22 at 9 08 20 AM" src="https://user-images.githubusercontent.com/22967723/105553050-b298de00-5cb9-11eb-86f1-00e60ca8a4cd.png">

Once you have a passing regex, our pre-push hook will not allow you to push your commit because the other commands currently do not pass their respective tests. To circumvent our pre-push hook, please push your changes using `git push --no-verify`, then make your pull request. 

**ACCEPTANCE CRITERIA**:
- [ ] The fixed regex passes all regex-related tests 
- [ ] The snapshot tests all *pass* and are not made obsolete by the new regex

**Comment by BoxenOfDonuts** [comment]
I can take a swing at this one

**Comment by twalton83** [comment]
Thanks!
